name: CI/CD Pipeline

on:
  push:
    branches:
      - DEV
  pull_request:
    branches:
      - DEV

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install


      - name: Build
        if: github.event_name == 'push' && github.ref == 'refs/heads/DEV'
        run: npm run build

      - name: Deploy to DigitalOcean
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/DEV'
        run: |
          curl -X POST "https://api.digitalocean.com/v2/apps/${{ secrets.DO_APP_ID }}/deployments" \
          -H "Authorization: Bearer ${{ secrets.DO_API_TOKEN }}" \
          -H "Content-Type: application/json"
