name: Deploy to DigitalOcean Prod Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Trigger Deployment in DigitalOcean
        run: bash .github/scripts/deploy_to_do.sh
        env:
          DIGITAL_OCEAN_APP_ID: ${{ secrets.DO_APP_ID }}
          DIGITAL_OCEAN_API_TOKEN: ${{ secrets.DO_API_TOKEN }}

      - name: Check Deployment Status in DigitalOcean
        run: bash .github/scripts/check_deployment_status.sh
        env:
          DIGITAL_OCEAN_APP_ID: ${{ secrets.DO_APP_ID }}
          DIGITAL_OCEAN_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DEPLOYMENT_ID: ${{ env.DEPLOYMENT_ID }}
