name: PROD CI/CD Pipeline Test and Build

on:
  push:
    branches:
      - PROD 
  pull_request:
    branches:
      - PROD

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies

        run: npm install
  
      # - name: Run tests
      #   run: npm test
      
      - name: Build project
        run: npm run build
      
      - name: Notify Success in Telegram
        if: success()
        run: bash .github/scripts/notify_telegram_success.sh
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MESSAGE: "Build and test completed for PROD branch. Deploy to DigitalOcean?"

      - name: Notify Failure in Telegram
        if: failure()
        run: bash .github/scripts/notify_telegram_failure.sh
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MESSAGE: "Error encountered in build/test process for PROD branch."
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
